const Items = [
  {
    id: 1,
    mainImage:
      "https://res.cloudinary.com/dxx3064r3/image/upload/v1752164131/vyavar1_mp83ae.png",
    img: [
      "https://res.cloudinary.com/dxx3064r3/image/upload/v1752164131/vyavar1_mp83ae.png",
      "https://res.cloudinary.com/dxx3064r3/image/upload/v1752164148/vyavar3_winto5.png",
      "https://res.cloudinary.com/dxx3064r3/image/upload/v1752164144/vyavar2_eamyow.png",
      "https://res.cloudinary.com/dxx3064r3/image/upload/v1752164152/vyavar4_resbga.png",
    ],
    features: [
      "UserPanel",
      "Admin Panel",
      "Delivery Panel",
      "Home",
      "About",
      "Categories",
      "Filter",
      "Cart Management",
      "Image Upload",
      "Advertisement",
      "Payment",
      "Favorites",
      "Review",
      "Product View",
      "Revenew",
      "Sales",
      "Email Notification",
      "Register",
      "Login",
      "Built a feature-rich eCommerce platform enabling seamless product browsing,purchasing, and order management",
      "Responsive Design",
      "404 Page and many more.",
    ],
    technologies: [
      "React Js",
      "Chakra UI",
      "Redux",
      "Cloudinary",
      "React icons",
      "Node Mailer",
      "RazorPay",
    ],
    title: "VIYAVAR E-commerce Website",
    description:
      "Built a feature-rich eCommerce platform enabling seamless product browsing,purchasing, and order management",
    category: "business",
    liveLink: "https://vyavar.vercel.app/?gender=Men",
    codeLink: "https://github.com/Dushyanth099/Vyavar",
  },
  {
    id: 2,
    mainImage:
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701479/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-4_kmaye9.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701456/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-1_jppjdj.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701463/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-2_ptr4lg.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682701467/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-3_gjle1m.png",
    ],
    features: [
      "User registration and login",
      "Authentication using JWT Tokens",
      "Inventory",
      "CRUD operations (Story create, read, update and delete)",
      "Sales",
      "HR",
      "Calender",
      "Finance Modules",
      "Billing",
      "Invoice",
      "404 Page and many more.",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Icons",
      "Axios",
      "CSS",
      "UUID",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Mongoose",
      "Express Asynsc Handler",
      "Json Web Token",
      "Bcryptjs",
      "Nodemailer",
      "Dontenv",
      "Multer",
      "Cors",
    ],
    title: "ERP Management System",
    description:
      "Developed a comprehensive ERP web application to streamline business,operations, including inventory, sales, HR, and finance modules",
    category: "business",
    liveLink: "https://ERP.vercel",
    codeLink: "https://github.com/Dushyanth099/Billing_software",
  },
  {
    id: 3,
    mainImage:
      "https://res.cloudinary.com/dxx3064r3/image/upload/v1752164337/muthu1_en96qe.png",
    img: [
      "https://res.cloudinary.com/dxx3064r3/image/upload/v1752164337/muthu1_en96qe.png",
      "https://res.cloudinary.com/dxx3064r3/image/upload/v1752164365/muthu3_hjuix6.png",
      "https://res.cloudinary.com/dxx3064r3/image/upload/v1752164376/muthu2_t2wqal.png",
    ],
    features: [
      "Home",
      "Products",
      "Machineries",
      "Blog",
      "Contact",
      "About",
      "Image Upload",
      "Animation",
      "Parallax",
      "GSAP",
      "404 Page and many more",
      "Responsive Design",
    ],
    technologies: [
      "HTML",
      "CSS",
      "Javascript",
      "Bootstrap",
      "Gsap",
      "Parallax",
      "Swiper",
      "FontAwesome",
      "ReactIcons",
    ],
    title: "MUTHU Printers-Printing Website",
    description:
      "Designed and built a business website to promote printing services and attract local clients.",
    category: "personal",
    liveLink: "https://muthuprinters.netlify.app/home",
    codeLink: "https://github.com/Dushyanth099/Muthuprinters",
  },
  {
    id: 4,
    mainImage:
      "https://res.cloudinary.com/dxx3064r3/image/upload/v1752164442/platos1_tqrajy.png",
    img: [
      "https://res.cloudinary.com/dxx3064r3/image/upload/v1752164442/platos1_tqrajy.png",
      "https://res.cloudinary.com/dxx3064r3/image/upload/v1752164461/platos2_nqi7vm.png",
      "https://res.cloudinary.com/dxx3064r3/image/upload/v1752164482/platos3_pg8kkv.png",
    ],
    features: [
      "Home",
      "About",
      "Academics",
      "ExtraCurricular Activities",
      "Achievements",
      "Policy",
      "Contact",
      "Parallax",
      "Gsap",
      "Swiper Js",
      "404 Page and many more",
      "Responsive Design",
    ],
    technologies: [
      "HTML",
      "CSS",
      "Javascript",
      "Bootstrap",
      "Gsap",
      "Parallax",
      "Swiper JS",
      "FontAwesome",
      "ReactIcons",
    ],
    title: "Platos Academy - School Website",
    description:
      "Developed a responsive and interactive school website to showcase academic,programs, achievements, and admission details.",
    category: "personal",
    liveLink: "https://platosacademytiruppur.netlify.app/",
    codeLink: "https://github.com/Dushyanth099/Platos",
  },
  // {
  //   id: 5,
  //   mainImage:
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-1_yhedpu.png",
  //   img: [
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-1_yhedpu.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-2_uktrxk.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-3_s1js9i.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-4_sb9ga6.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683869748/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-5_wrxlr7.png",
  //   ],
  //   features: [
  //     "Add Student",
  //     "Edit Student",
  //     "Remove Student",
  //     "No Student Page",
  //     "Responsive Design",
  //     "404 Page and many more",
  //   ],
  //   technologies: [
  //     "React",
  //     "React Hooks",
  //     "React Router Dom",
  //     "Axios",
  //     "Bootstrap",
  //     "React Icons",
  //     "Sweet Alert2",
  //     "Node JS",
  //     "Express JS",
  //     "Cors",
  //     "Mongoose",
  //     "Dotenv",
  //     "Nodemon",
  //     "MongoDB",
  //   ],
  //   title: "Student Management System",
  //   description:
  //     "Fullstack open source student management system application made with MongoDB, Express, React & Nodejs (MERN)",
  //   category: "business",
  //   liveLink: "https://sttiss.vercel.app/",
  //   codeLink: "https://github.com/berthutapea/mern-student-management-system",
  // },
  // {
  //   id: 6,
  //   mainImage:
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682964283/Blog%20Portfolio%20Gilbert/Project/mario-jump-game/img-2_iwduig.png",
  //   img: [
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682964283/Blog%20Portfolio%20Gilbert/Project/mario-jump-game/img-1_gpiiro.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682964283/Blog%20Portfolio%20Gilbert/Project/mario-jump-game/img-2_iwduig.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682964283/Blog%20Portfolio%20Gilbert/Project/mario-jump-game/img-3_sk2hyn.png",
  //   ],
  //   features: [
  //     "Mobile Responsive",
  //     "Beautiful Animations",
  //     "Rapid Controls",
  //     "High Score",
  //     "Mario Background Music",
  //     "Jump & Game Over Sound Effect",
  //   ],
  //   technologies: [
  //     "React",
  //     "CSS",
  //     "React Hooks",
  //     "React Router",
  //     "React Redux",
  //   ],
  //   title: "Mario Jump",
  //   description:
  //     "Mario Jump is an endless running game inspired by the famous Google Chrome's T-Rex Dinosaur Game 🦖. The game is built entirely with ReactJS ⚛ and Redux Toolkit 🔧.",
  //   category: "game",
  //   liveLink: "https://mariojumpp.vercel.app/",
  //   codeLink: "https://github.com/berthutapea/mario-jump-game",
  // },
  // {
  //   id: 7,
  //   mainImage:
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682944695/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-3_t6uxoj.png",
  //   img: [
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-1_gqero4.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-2_ukjdh2.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682944695/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-3_t6uxoj.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-4_btevir.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-5_oakjx2.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682944092/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-6_pqefy9.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-7_wfrvb7.png",
  //   ],
  //   features: [
  //     "User registration and login",
  //     "Select the type of question and the difficulty level of the question",
  //     "Juis time is running and after the time is up it stops automatically",
  //     "The final results of the answers answered will be shown",
  //     "Incorrect and correct answer results will be displayed",
  //     "Responsive Design",
  //   ],
  //   technologies: [
  //     "React",
  //     "React Vite",
  //     "Tailwind CSS",
  //     "Firebase Authentication",
  //     "Framer Motion",
  //     "React Firebase Hooks",
  //     "React Icons",
  //   ],
  //   title: "Bert Quiz",
  //   description: "Fullstack open source quiz application",
  //   category: "personal",
  //   liveLink: "https://bertquiz.vercel.app/",
  //   codeLink: "https://github.com/berthutapea/react-quiz",
  // },
  // {
  //   id: 8,
  //   mainImage:
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-1_q5d6pn.png",
  //   img: [
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-1_q5d6pn.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683033411/Blog%20Portfolio%20Gilbert/Project/shopify/img-2_nko9ic.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683033413/Blog%20Portfolio%20Gilbert/Project/shopify/img-3_rnhbr1.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-4_ks8lck.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683033409/Blog%20Portfolio%20Gilbert/Project/shopify/img-5_eotroj.png",
  //     "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-6_fgpzef.png",
  //   ],
  //   features: [
  //     "Mobile Responsive",
  //     "Beautiful Animations",
  //     "Product",
  //     "Pricing",
  //     "Testimonial",
  //     "Contact",
  //   ],
  //   technologies: [
  //     "React",
  //     "React Vite",
  //     "Tailwind CSS",
  //     "Framer Motion",
  //     "React Icons",
  //     "React Hooks",
  //   ],
  //   title: "Shopify",
  //   description: "Open source landing page shopify application",
  //   category: "personal",
  //   liveLink: "https://shopifyy.vercel.app/",
  //   codeLink: "https://github.com/berthutapea/react-shopify-landing",
  // },
];

export default Items;
